import { useLanguage } from '@/contexts/LanguageContext';

export const useServices = () => {
  const { t } = useLanguage();
  
  return [
    {
      id: 1,
      title: t('solutions.services.aiWorkshopPlanning.title'),
      intro: t('solutions.services.aiWorkshopPlanning.intro'),
      type: 'AI',
      priceModel: 'Fixed',
    },
    {
      id: 2,
      title: t('solutions.services.smartAppointmentBooking.title'),
      intro: t('solutions.services.smartAppointmentBooking.intro'),
      type: 'AI',
      priceModel: 'Fixed',
    },
    {
      id: 3,
      title: t('solutions.services.integratedOnlinePayment.title'),
      intro: t('solutions.services.integratedOnlinePayment.intro'),
      type: 'AI',
      priceModel: 'Fixed',
    },
    {
      id: 4,
      title: t('solutions.services.oneTimeConsulting.title'),
      intro: t('solutions.services.oneTimeConsulting.intro'),
      type: 'Consulting',
      priceModel: 'Custom',
    },
    {
      id: 5,
      title: t('solutions.services.fullExecution.title'),
      intro: t('solutions.services.fullExecution.intro'),
      type: 'Field',
      priceModel: 'Estimate',
    },
    {
      id: 6,
      title: t('solutions.services.fieldAudit.title'),
      intro: t('solutions.services.fieldAudit.intro'),
      type: 'Field',
      priceModel: 'Estimate',
    },
    {
      id: 7,
      title: t('solutions.services.staffingTraining.title'),
      intro: t('solutions.services.staffingTraining.intro'),
      type: 'Field',
      priceModel: 'Estimate',
    },
    {
      id: 8,
      title: t('solutions.services.equipmentProcurement.title'),
      intro: t('solutions.services.equipmentProcurement.intro'),
      type: 'Field',
      priceModel: 'Estimate',
    },
    {
      id: 9,
      title: t('solutions.services.digitalLaunchPackage.title'),
      intro: t('solutions.services.digitalLaunchPackage.intro'),
      type: 'AI',
      priceModel: 'Fixed',
    },
    {
      id: 10,
      title: t('solutions.services.aiExplainerVideo.title'),
      intro: t('solutions.services.aiExplainerVideo.intro'),
      type: 'AI',
      priceModel: 'Fixed',
    },
    {
      id: 11,
      title: t('solutions.services.preBuiltPackages.title'),
      intro: t('solutions.services.preBuiltPackages.intro'),
      type: 'Consulting',
      priceModel: 'Fixed',
    },
    {
      id: 12,
      title: t('solutions.services.transparentPricing.title'),
      intro: t('solutions.services.transparentPricing.intro'),
      type: 'Consulting',
      priceModel: 'Custom',
    },
    {
      id: 13,
      title: t('solutions.services.tieredAccess.title'),
      intro: t('solutions.services.tieredAccess.intro'),
      type: 'Consulting',
      priceModel: 'Custom',
    },
    {
      id: 14,
      title: t('solutions.services.aiRecommendation.title'),
      intro: t('solutions.services.aiRecommendation.intro'),
      type: 'AI',
      priceModel: 'Fixed',
    },
    {
      id: 15,
      title: t('solutions.services.multipleAccessPoints.title'),
      intro: t('solutions.services.multipleAccessPoints.intro'),
      type: 'AI',
      priceModel: 'Fixed',
    },
    {
      id: 16,
      title: t('solutions.services.mobileWorkshopSetup.title'),
      intro: t('solutions.services.mobileWorkshopSetup.intro'),
      type: 'Field',
      priceModel: 'Estimate',
    },
    {
      id: 17,
      title: t('solutions.services.cctvMonitoring.title'),
      intro: t('solutions.services.cctvMonitoring.intro'),
      type: 'Field',
      priceModel: 'Estimate',
    },
    {
      id: 18,
      title: t('solutions.services.nightShiftEnablement.title'),
      intro: t('solutions.services.nightShiftEnablement.intro'),
      type: 'Field',
      priceModel: 'Estimate',
    },
    {
      id: 19,
      title: t('solutions.services.digitalMysteryShopper.title'),
      intro: t('solutions.services.digitalMysteryShopper.intro'),
      type: 'AI',
      priceModel: 'Fixed',
    },
    {
      id: 20,
      title: t('solutions.services.googleWebsiteMaintenance.title'),
      intro: t('solutions.services.googleWebsiteMaintenance.intro'),
      type: 'AI',
      priceModel: 'Fixed',
    },
    {
      id: 21,
      title: t('solutions.services.loyaltyPrograms.title'),
      intro: t('solutions.services.loyaltyPrograms.intro'),
      type: 'AI',
      priceModel: 'Fixed',
    },
    {
      id: 22,
      title: t('solutions.services.ownerLeadershipCoaching.title'),
      intro: t('solutions.services.ownerLeadershipCoaching.intro'),
      type: 'Consulting',
      priceModel: 'Custom',
    },
    {
      id: 23,
      title: t('solutions.services.customerFeedbackSurvey.title'),
      intro: t('solutions.services.customerFeedbackSurvey.intro'),
      type: 'AI',
      priceModel: 'Fixed',
    },
    {
      id: 24,
      title: t('solutions.services.professionalQuotationDesign.title'),
      intro: t('solutions.services.professionalQuotationDesign.intro'),
      type: 'AI',
      priceModel: 'Fixed',
    },
  ];
};

// For backward compatibility, export a default services array (English)
export const services = [
  {
    id: 1,
    title: 'AI Workshop Planning Assistant',
    intro: 'Let our AI design a complete workshop layout, equipment list, and financial plan for you.',
    type: 'AI',
    priceModel: 'Fixed',
  },
  {
    id: 2,
    title: 'Smart Appointment Booking',
    intro: 'An automated booking system that integrates with your calendar and sends reminders.',
    type: 'AI',
    priceModel: 'Fixed',
  },
  {
    id: 3,
    title: 'Integrated Online Payment',
    intro: 'Accept payments from your customers securely through our integrated Stripe solution.',
    type: 'AI',
    priceModel: 'Fixed',
  },
  {
    id: 4,
    title: 'One-Time Consulting Services',
    intro: 'Get expert advice on any aspect of your workshop business, from marketing to operations.',
    type: 'Consulting',
    priceModel: 'Custom',
  },
  {
    id: 5,
    title: 'Full Execution of Workshop Plans',
    intro: 'We take your AI-generated plan and turn it into a reality, managing the entire setup process.',
    type: 'Field',
    priceModel: 'Estimate',
  },
  {
    id: 6,
    title: 'Field Audit & Evaluation Trips',
    intro: 'Our experts visit your workshop to provide a comprehensive audit and recommendations for improvement.',
    type: 'Field',
    priceModel: 'Estimate',
  },
  {
    id: 7,
    title: 'Staffing & Training Services',
    intro: 'We help you find, hire, and train the right people for your workshop.',
    type: 'Field',
    priceModel: 'Estimate',
  },
  {
    id: 8,
    title: 'Equipment Procurement Agency',
    intro: 'We source and procure the best equipment for your workshop at competitive prices.',
    type: 'Field',
    priceModel: 'Estimate',
  },
  {
    id: 9,
    title: 'Digital Launch Package',
    intro: 'A complete package to launch your workshop online, including a website, social media, and Google My Business setup.',
    type: 'AI',
    priceModel: 'Fixed',
  },
  {
    id: 10,
    title: 'AI Explainer Video & Onboarding',
    intro: 'An AI-generated video to explain your services to customers and onboard new employees.',
    type: 'AI',
    priceModel: 'Fixed',
  },
  {
    id: 11,
    title: 'Pre-built Service Packages',
    intro: 'Choose from our pre-built packages for launch, growth, and support.',
    type: 'Consulting',
    priceModel: 'Fixed',
  },
  {
    id: 12,
    title: 'Transparent Pricing Models',
    intro: 'Clear and upfront pricing for all our services.',
    type: 'Consulting',
    priceModel: 'Custom',
  },
  {
    id: 13,
    title: 'Tiered Access Communication',
    intro: 'Choose your level of support with our tiered communication plans.',
    type: 'Consulting',
    priceModel: 'Custom',
  },
  {
    id: 14,
    title: 'AI-Powered Service Recommendation',
    intro: 'Our AI recommends the best services for your workshop based on your needs.',
    type: 'AI',
    priceModel: 'Fixed',
  },
  {
    id: 15,
    title: 'Multiple Access Points to AI Suite',
    intro: 'Access our AI suite from anywhere, on any device.',
    type: 'AI',
    priceModel: 'Fixed',
  },
  {
    id: 16,
    title: 'Mobile Workshop Setup',
    intro: 'We help you set up a mobile workshop to serve customers on the go.',
    type: 'Field',
    priceModel: 'Estimate',
  },
  {
    id: 17,
    title: 'CCTV & Behavioral Monitoring Installations',
    intro: 'Install CCTV and behavioral monitoring systems to improve security and efficiency.',
    type: 'Field',
    priceModel: 'Estimate',
  },
  {
    id: 18,
    title: 'Night-Shift Enablement Services',
    intro: "We help you set up a night shift to maximize your workshop's productivity.",
    type: 'Field',
    priceModel: 'Estimate',
  },
  {
    id: 19,
    title: 'Digital Mystery Shopper Testing',
    intro: 'Our digital mystery shoppers test your online presence and provide feedback for improvement.',
    type: 'AI',
    priceModel: 'Fixed',
  },
  {
    id: 20,
    title: 'Google + Website Maintenance Plans',
    intro: 'Keep your website and Google My Business profile up-to-date with our maintenance plans.',
    type: 'AI',
    priceModel: 'Fixed',
  },
  {
    id: 21,
    title: 'Workshop Loyalty Programs',
    intro: 'Create a loyalty program to reward your customers and keep them coming back.',
    type: 'AI',
    priceModel: 'Fixed',
  },
  {
    id: 22,
    title: 'Owner Leadership Coaching',
    intro: 'One-on-one coaching to help you become a more effective leader.',
    type: 'Consulting',
    priceModel: 'Custom',
  },
  {
    id: 23,
    title: 'Customer Feedback Survey Systems',
    intro: 'Set up a system to collect and analyze customer feedback.',
    type: 'AI',
    priceModel: 'Fixed',
  },
  {
    id: 24,
    title: 'Professional Quotation Design Packs',
    intro: 'Design professional quotations that will impress your customers.',
    type: 'AI',
    priceModel: 'Fixed',
  },
];
