import { NextApiRequest, NextApiResponse } from 'next';
import PDFDocument from 'pdfkit';
import { createWriteStream } from 'fs';
import { join } from 'path';

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method !== 'POST') {
    return res.status(405).json({ message: 'Method not allowed' });
  }

  try {
    const { plan, workshopData, imageUrl } = req.body;

    // Create PDF document
    const doc = new PDFDocument({ 
      size: 'A4',
      margin: 50,
      info: {
        Title: 'TeraLab Workshop Plan',
        Author: 'TeraLab AI Assistant',
        Subject: 'Automotive Workshop Business Plan',
      }
    });

    // Set response headers for PDF download
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename=teralab-workshop-plan.pdf');

    // Pipe PDF to response
    doc.pipe(res);

    // Add TeraLab header
    doc.fontSize(24)
       .fillColor('#1E40AF')
       .text('TeraLab', 50, 50);
       
    doc.fontSize(16)
       .fillColor('#6B7280')
       .text('AI-Generated Workshop Plan', 50, 80);

    doc.moveDown(2);

    // Add workshop data summary
    doc.fontSize(18)
       .fillColor('#000000')
       .text('Workshop Specifications', 50, 120);

    doc.fontSize(12)
       .text(`Business Type: ${workshopData.businessType}`, 50, 150)
       .text(`Location: ${workshopData.location}`, 50, 170)
       .text(`Budget: ${workshopData.budget}`, 50, 190)
       .text(`Services: ${workshopData.services.join(', ')}`, 50, 210)
       .text(`Timeline: ${workshopData.timeline}`, 50, 230)
       .text(`Space Size: ${workshopData.spaceSize}`, 50, 250);

    doc.moveDown(2);

    // Add generated plan content
    doc.fontSize(14)
       .text('Detailed Business Plan', 50, 300);

    doc.fontSize(10)
       .text(plan, 50, 320, {
         width: 500,
         align: 'left'
       });

    // Add footer
    doc.fontSize(8)
       .fillColor('#6B7280')
       .text('Generated by TeraLab AI Assistant - Visit teralab.io for implementation services', 
             50, 750, { align: 'center' });

    // Finalize PDF
    doc.end();

  } catch (error) {
    console.error('PDF Generation Error:', error);
    res.status(500).json({
      success: false,
      message: 'Error generating PDF',
      error: process.env.NODE_ENV === 'development' ? (error as Error).message : 'Internal server error'
    });
  }
}